### ISSUE TITLE
[Oct 18] Implement the function of drawing the stats chart

### ISSUE THREAD

**Issue by YouthBread** [YouthBread/kobe-bryant-dataviz-project#3]
- The stats chart can be various in different types, like bar chart, line chart or pie chart.
- Also included the heat map under the court.

**Comment by RainismZ** [comment]
Heat map is an excellent idea to show us the hit rate on the whole court of the player.

**Comment by curran** [comment]
d3-contour might be a good option for implementing a HeatMap https://github.com/d3/d3-contour
